trigger:
  batch: true
  branches:
    include:
      - xdebug_3_0
      - master

jobs:
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_MASTER'
      phpVersion: 'master'
      configurationParameters: '--enable-debug --disable-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_80'
      phpVersion: '8.0.0'
      configurationParameters: '--enable-debug --disable-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_74'
      phpVersion: '7.4.13'
      configurationParameters: '--enable-debug --disable-maintainer-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_73'
      phpVersion: '7.3.25'
      configurationParameters: '--enable-debug --disable-maintainer-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_MASTER_ZTS'
      phpVersion: 'master'
      configurationParameters: '--enable-debug --enable-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_80_ZTS'
      phpVersion: '8.0.0'
      configurationParameters: '--enable-debug --enable-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_74_ZTS'
      phpVersion: '7.4.13'
      configurationParameters: '--enable-debug --enable-maintainer-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'OSX_PHP_73_ZTS'
      phpVersion: '7.3.25'
      configurationParameters: '--enable-debug --enable-maintainer-zts'
